name: robotframework

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - nodejs=16.14.2
  - pip

  - pip:
    - robotframework-butlerhat[full]
    - git+https://github.com/robocorp/robotframework-lsp.git@master#subdirectory=robotframework-interactive/src
    - git+https://github.com/robocorp/robotframework-lsp.git@master#subdirectory=robocorp-python-ls-core/src
    - httpx
