name: base

channels:
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
    - robotframework-dist-butlerhat[full] @ git+https://{GITHUB_ACCESS_TOKEN}@github.com/ButlerHat/robotframework-dist-butlerhat.git
    - git+https://github.com/robocorp/robotframework-lsp.git@master#subdirectory=robotframework-interactive/src
    - git+https://github.com/robocorp/robotframework-lsp.git@master#subdirectory=robocorp-python-ls-core/src
    - pytest
    - httpx
