version: '3.7'
services:
  interperter_prod:
    image: butlerhat/interperter_prod:latest
    container_name: interperter_prod
    user: vscode
    init: true
    volumes:
      - ${HOST_HOME}/.cloudflared:/home/vscode/.cloudflared:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    command: bash .devcontainer/postCreateCommand.sh

networks:
  external:
    name: net_robot
