version: '3.7'
services:
  interperter_prod:
    image: butlerhat/interpreter_prod:latest
    container_name: interpreter_prod
    user: vscode
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    command: bash .devcontainer/prod/postCreateCommand.sh
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8000/health"]
      interval: 1m
      timeout: 1m
      retries: 3

  interperter_prod_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: interperter_prod_tunnel
    networks:
      - external
    depends_on:
      interperter_prod:
        condition: service_healthy
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${TUNNEL_TOKEN}

  # interperter_prod_tunnel_vnc:
  #   image: cloudflare/cloudflared:latest
  #   container_name: interperter_prod_tunnel_vnc
  #   networks:
  #     - external
  #   depends_on:
  #     interperter_prod:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   command:
  #     - tunnel
  #     - --no-autoupdate
  #     - run
  #     - --token
  #     - ${TUNNEL_TOKEN_VNC}

networks:
  external:
    name: net_robot
