name: robotframework

channels:
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robotframework-interactive/src
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robocorp-python-ls-core/src
    - pytest
    - httpx
    - python-multipart
    - typing_extensions