name: robotframework

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - nodejs=16.14.2
  - pip

  - pip:
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robotframework-interactive/src
    - git+https://github.com/robocorp/robotframework-lsp.git@release-robotframework-lsp#subdirectory=robocorp-python-ls-core/src
    - robotframework-butlerhat[browser_stealth]
    - httpx
    - python-multipart
    - typing_extensions