version: '3.7'
services:
  gpt4api_prod:
    image: butlerhat/gpt4api_prod:latest
    container_name: gpt4api_prod
    user: vscode
    init: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    command: bash .devcontainer/prod_gpt4/postCreateCommand.sh
    volumes:
      - gpt4_cookies:/tmp/cookies
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8000/health"]
      interval: 5s
      timeout: 1m
      retries: 12

  gpt4api_prod_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: gpt4api_prod_tunnel
    networks:
      - external
    depends_on:
      gpt4api_prod:
        condition: service_healthy
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${TUNNEL_TOKEN}

  gpt4api_prod_tunnel_vnc:
    image: cloudflare/cloudflared:latest
    container_name: gpt4api_prod_tunnel_vnc
    networks:
      - external
    depends_on:
      gpt4api_prod:
        condition: service_healthy
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${TUNNEL_TOKEN_VNC}

volumes:
  gpt4_cookies:
  
networks:
  external:
    name: net_robot
