version: '3.7'
services:
  gpt4api_prod:
    image: butlerhat/gpt4api_prod
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PYPI_USER: ${PYPI_USER}
        PYPI_PASS: ${PYPI_PASS}
      target: prod_gpt4
