version: '3.7'
services:
  interpreter_dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      target: base
    container_name: interpreter_dev
    init: true
    user: vscode
    volumes:
      - ../../../..:/workspaces/ai-butlerhat:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:cached
      - ${HOME}/.cloudflared:/home/vscode/.cloudflared:cached
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - external
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  external:
    name: net_robot