name: Build and deploy interpreter app
on:
  push:
    branches: [ master ]
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: omen-ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set prod devcontainer
      run: |
        cp .devcontainer/prod/devcontainer.json .devcontainer/
        
        echo 'USER_ID=1000' >> .devcontainer/.env
        echo 'GROUP_ID=1000' >> .devcontainer/.env
        echo 'PYPI_USER='"'"'${{ secrets.PYPI_USER }}'"'"'' >> .devcontainer/prod/.env
        echo 'PYPI_PASS='"'"'${{ secrets.PYPI_PASS }}'"'"'' >> .devcontainer/prod/.env
        echo 'TUNNEL_TOKEN='"'"'${{ secrets.TUNNEL_TOKEN }}'"'"'' >> .devcontainer/prod/.env
        echo 'TUNNEL_TOKEN_VNC='"'"'${{ secrets.TUNNEL_TOKEN_VNC }}'"'"'' >> .devcontainer/prod/.env

    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pre-build image
      uses: devcontainers/ci@v0.3
      with:
        imageName: butlerhat/interpreter_prod
        cacheFrom: butlerhat/interpreter_prod
        push: always

    - name: Deploy
      run: |
        docker compose -f .devcontainer/prod/docker-compose-deploy.yml up -d
      